# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastBump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bump_at', models.DateTimeField(db_index=True, verbose_name='吸奶时间')),
                ('amount', models.IntegerField(verbose_name='数量(ml)')),
                ('record_at', models.DateTimeField(auto_now_add=True, verbose_name='纪录时间')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkMilk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_at', models.DateTimeField(db_index=True, verbose_name='喝奶时间')),
                ('amount', models.IntegerField(verbose_name='数量(ml)')),
                ('drink_type', models.CharField(max_length=10, verbose_name='类型')),
                ('record_at', models.DateTimeField(auto_now_add=True, verbose_name='纪录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Pee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(db_index=True, verbose_name='日期')),
                ('pee_type', models.IntegerField(verbose_name='类型')),
                ('amount', models.IntegerField(verbose_name='次数')),
                ('record_at', models.DateTimeField(auto_now_add=True, verbose_name='纪录时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start', models.DateTimeField(db_index=True, verbose_name='睡眠开始')),
                ('sleep_end', models.DateTimeField(verbose_name='睡眠结束')),
                ('record_at', models.DateTimeField(auto_now_add=True, verbose_name='纪录时间')),
            ],
        ),
    ]
